dist: xenial

services:
  - docker

language: go

go:
  - 1.12.1

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  make test

script:
  - make container
  - make docker-push
