dist: xenial

services:
  - docker

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.1

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  make test

script:
  - make container
